server:
  port: 8090
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /school
spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unlonely?&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 12345678
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379